# Generated by Django 4.0.6 on 2022-07-28 21:13

from django.db import migrations, models
import image_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_api.models.upload_image_to)),
                ('ascii_image', models.FileField(blank=True, null=True, upload_to=image_api.models.upload_ascii_image_to)),
            ],
        ),
    ]
